
export const initialSetupEntries = [
    { location: 'leftDummyPart', name: 'helmet', link: 'https://sabzero.biz/croomTemplate/assets/img/helmet.png', typeid: [1] },
    { location: 'leftDummyPart', name: 'armor', link: 'https://sabzero.biz/croomTemplate/assets/img/armor.png', typeid: [3] },
    { location: 'leftDummyPart', name: 'belt', link: 'https://sabzero.biz/croomTemplate/assets/img/belt.png', typeid: [6] }, //поЯс
    { location: 'leftDummyPart', name: 'boots', link: 'https://sabzero.biz/croomTemplate/assets/img/boots.png', typeid: [11]  },
    { location: 'leftDummyPart', name: 'earring1', link: 'https://sabzero.biz/croomTemplate/assets/img/earring.png', typeid: [55]  },
    { location: 'leftDummyPart', name: 'ring1', link: 'https://sabzero.biz/croomTemplate/assets/img/ring.png', typeid: [7]  },
    { location: 'leftDummyPart', name: 'ring2', link: 'https://sabzero.biz/croomTemplate/assets/img/ring.png', typeid: [7]  },
    { location: 'rightDummyPart', name: 'necklace', link: 'https://sabzero.biz/croomTemplate/assets/img/necklace.png', typeid: [2] },
    { location: 'rightDummyPart', name: 'bracers', link: 'https://sabzero.biz/croomTemplate/assets/img/bracers.png', typeid: [5] }, //наручи
    { location: 'rightDummyPart', name: 'gloves', link: 'https://sabzero.biz/croomTemplate/assets/img/gloves.png', typeid: [4] }, //перчатки
    { location: 'rightDummyPart', name: 'leggings', link: 'https://sabzero.biz/croomTemplate/assets/img/leggings.png', typeid: [10] }, // поножи
    { location: 'rightDummyPart', name: 'earring2', link: 'https://sabzero.biz/croomTemplate/assets/img/earring.png', typeid: [55] }, //серьга
    { location: 'rightDummyPart', name: 'ring3', link: 'https://sabzero.biz/croomTemplate/assets/img/ring.png', typeid: [7]  },
    { location: 'rightDummyPart', name: 'ring4', link: 'https://sabzero.biz/croomTemplate/assets/img/ring.png', typeid: [7]  },
    { location: 'centerTopDummyPart', name: 'relic1', link: 'https://sabzero.biz/croomTemplate/assets/img/relic.png', typeid: [40] },
    { location: 'centerTopDummyPart', name: 'relic2', link: 'https://sabzero.biz/croomTemplate/assets/img/relic.png', typeid: [40] },
    { location: 'centerTopDummyPart', name: 'relic3', link: 'https://sabzero.biz/croomTemplate/assets/img/relic.png', typeid: [40] },
    { location: 'centerTopDummyPart', name: 'relic4', link: 'https://sabzero.biz/croomTemplate/assets/img/relic.png', typeid: [40] },
    { location: 'centerBottomDummyPart', name: 'weapons1', link: 'https://sabzero.biz/croomTemplate/assets/img/weapons.png', typeid: [8, 9, 12, 14, 15, 30, 31, 32, 33, 35, 37, 38, 39] },
    { location: 'centerBottomDummyPart', name: 'weapons2', link: 'https://sabzero.biz/croomTemplate/assets/img/weapons.png', typeid: [8, 9, 12, 14, 15, 30, 31, 32, 33, 35, 37, 38, 39] },
    // typeid: 8-пика, 9-топор, 12 меч, 15щит,30 посох, 31 молот,32 молот,33 топор, 35 клеймор, 37 жезл, 38 кастет, 39 кинжал,
  ]

// стартовый набор стат для первичного заполнения таблиц. Соотвествует расе человек. 
export const baseStatModule = [
  { type: 'stat', key: 'dstrength', name: 'Сила', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/strength.svg', minKey: 'minstrength' },
  { type: 'stat', key: 'ddexterity', name: 'Ловкість', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/dexterity.svg', minKey: 'mindexterity'  },
  { type: 'stat', key: 'dintel', name: 'Інтелект', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/intelligence.svg', minKey: 'minintel'  },
  { type: 'stat', key: 'dluck', name: 'Удача', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/luck.svg', minKey: 'minluck'  },
  { type: 'stat', key: 'dreaction', name: 'Реакція', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/reaction.svg', minKey: 'minreaction'  },
  { type: 'stat', key: 'dwisdom', name: 'Мудрість', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/wisdom.svg', minKey: 'minwisdom'  },
  { type: 'stat', key: 'dconst', name: 'Статура', summStatBase: 3, summStatBonusAndBase: 3, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/constitution.svg', minKey: 'minconst'  },
  { type: 'protectionMagick', key: 'whitemagicprotection', name: 'Світанок', summStatBase: 0, summStatBonusAndBase: 6, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/dawn.svg'},
  { type: 'protectionMagick', key: 'blackmagicprotection', name: 'Полнолуння', summStatBase: 0, summStatBonusAndBase: 6, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/full-Moon.svg' },
  { type: 'protectionMagick', key: 'astralmagicprotection', name: 'Астрал', summStatBase: 0, summStatBonusAndBase: 4, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/astral.svg' },
  { type: 'armor', key: 'headarmor', name: 'Голова', summStatBase: 0, summStatBonusAndBase: 0, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/armor_head.svg' },
  { type: 'armor', key: 'bodyarmor', name: 'Тулуб', summStatBase: 0, summStatBonusAndBase: 0, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/armor.svg' },
  { type: 'armor', key: 'lefthandarmor', name: 'Ліва рука', summStatBase: 0, summStatBonusAndBase: 0, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/leftHend.svg' },
  { type: 'armor', key: 'righthandarmor', name: 'Права рука', summStatBase: 0, summStatBonusAndBase: 0, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/rightHend.svg' },
  { type: 'armor', key: 'lagsarmor', name: 'Ноги', summStatBase: 0, summStatBonusAndBase: 0, link: 'https://sabzero.biz/croomTemplate/assets/img/icon/svg/leg-armor.svg' },
]

export const basickParamsRase = [
  {
    availableRaces: 'human', date: [
      {key: 'dstrength', count: 3 },
      {key: 'ddexterity', count: 3 },
      {key: 'dintel', count: 3 },
      {key: 'dluck', count: 3 },
      {key: 'dreaction', count: 3 },
      {key: 'dwisdom', count: 3 },
      {key: 'dconst', count: 3 },
      {key: 'whitemagicprotection', count: 6 },
      {key: 'blackmagicprotection', count: 6 },
      {key: 'astralmagicprotection', count: 4 },
    ]
  },
  {
    availableRaces: 'gnom', date: [
      {key: 'dstrength', count: 4 },
      {key: 'ddexterity', count: 2 },
      {key: 'dintel', count: 2 },
      {key: 'dluck', count: 3 },
      {key: 'dreaction', count: 2 },
      {key: 'dwisdom', count: 4 },
      {key: 'dconst', count: 4 },
      {key: 'whitemagicprotection', count: 4 },
      {key: 'blackmagicprotection', count: 8 },
      {key: 'astralmagicprotection', count: 4 },
    ]
  },
  {
    availableRaces: 'elf', date: [
      {key: 'dstrength', count: 3 },
      {key: 'ddexterity', count: 5 },
      {key: 'dintel', count: 3 },
      {key: 'dluck', count: 2 },
      {key: 'dreaction', count: 2 },
      {key: 'dwisdom', count: 3 },
      {key: 'dconst', count: 3 },
      {key: 'whitemagicprotection', count: 8 },
      {key: 'blackmagicprotection', count: 4 },
      {key: 'astralmagicprotection', count: 4 },
    ]
  },
  {
    availableRaces: 'vampire', date: [
      {key: 'dstrength', count: 3 },
      {key: 'ddexterity', count: 3 },
      {key: 'dintel', count: 3 },
      {key: 'dluck', count: 4 },
      {key: 'dreaction', count: 2 },
      {key: 'dwisdom', count: 3 },
      {key: 'dconst', count: 3 },
      {key: 'whitemagicprotection', count: 6 },
      {key: 'blackmagicprotection', count: 6 },
      {key: 'astralmagicprotection', count: 4 },
    ]
  },
  {
    availableRaces: 'ork', date: [
      {key: 'dstrength', count: 4 },
      {key: 'ddexterity', count: 3 },
      {key: 'dintel', count: 2 },
      {key: 'dluck', count: 4 },
      {key: 'dreaction', count: 3 },
      {key: 'dwisdom', count: 1 },
      {key: 'dconst', count: 4 },
      {key: 'whitemagicprotection', count: 9 },
      {key: 'blackmagicprotection', count: 9 },
      {key: 'astralmagicprotection', count: 0 },
    ]
  },
  {
    availableRaces: 'trol', date: [
      {key: 'dstrength', count: 5 },
      {key: 'ddexterity', count: 2 },
      {key: 'dintel', count: 1 },
      {key: 'dluck', count: 3 },
      {key: 'dreaction', count: 3 },
      {key: 'dwisdom', count: 2 },
      {key: 'dconst', count: 5 },
      {key: 'whitemagicprotection', count: 7 },
      {key: 'blackmagicprotection', count: 5 },
      {key: 'astralmagicprotection', count: 4 },
      {key: 'fortress', count: 1 },
    ]
  },
]

// массив для работы пока создается
export const baseStatClasses = [
    {
        "id": 1,
        "name": "Джаггернаут",
        "name_en": "Juggernaut",
        "parent": 0,
        "parent_name": null,
        "number": 4,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 2,
        "name": "Защитник",
        "name_en": "Defender",
        "parent": 1,
        "parent_name": "Juggernaut",
        "number": 1,
        "minstrength": 16,
        "mindexterity": null,
        "minreaction": 12,
        "minconst": 29,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 4,
        "dintel": null,
        "dwisdom": 2,
        "dluck": 4,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 3,
        "name": "Гвардеец",
        "name_en": "Guardsman",
        "parent": 1,
        "parent_name": "Juggernaut",
        "number": 2,
        "minstrength": 27,
        "mindexterity": null,
        "minreaction": 18,
        "minconst": 44,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 11,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 9,
        "dintel": null,
        "dwisdom": 4,
        "dluck": 8,
        "astralmagicprotection": 2,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 4,
        "name": "Рыцарь",
        "name_en": "Knight",
        "parent": 1,
        "parent_name": "Juggernaut",
        "number": 3,
        "minstrength": 39,
        "mindexterity": null,
        "minreaction": 28,
        "minconst": 62,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 14,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 16,
        "dintel": null,
        "dwisdom": 7,
        "dluck": 15,
        "astralmagicprotection": 7,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 5,
        "name": "Кавалер",
        "name_en": "Cavalier",
        "parent": 1,
        "parent_name": "Juggernaut",
        "number": 4,
        "minstrength": 51,
        "mindexterity": null,
        "minreaction": 35,
        "minconst": 86,
        "minintel": null,
        "minwisdom": null,
        "minluck": 20,
        "minlevel": 17,
        "dstrength": null,
        "ddexterity": 7,
        "dreaction": null,
        "dconst": 23,
        "dintel": null,
        "dwisdom": 11,
        "dluck": 22,
        "astralmagicprotection": 7,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 6,
        "name": "Титан",
        "name_en": "Titan",
        "parent": 1,
        "parent_name": "Juggernaut",
        "number": 5,
        "minstrength": 60,
        "mindexterity": null,
        "minreaction": 43,
        "minconst": 100,
        "minintel": null,
        "minwisdom": null,
        "minluck": 42,
        "minlevel": 20,
        "dstrength": null,
        "ddexterity": 10,
        "dreaction": null,
        "dconst": 26,
        "dintel": null,
        "dwisdom": 14,
        "dluck": 25,
        "astralmagicprotection": 8,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 7,
        "name": "Исполин",
        "name_en": "Nephilim",
        "parent": 1,
        "parent_name": "Juggernaut",
        "number": 6,
        "minstrength": 75,
        "mindexterity": null,
        "minreaction": 58,
        "minconst": 115,
        "minintel": null,
        "minwisdom": null,
        "minluck": 57,
        "minlevel": 23,
        "dstrength": null,
        "ddexterity": 11,
        "dreaction": null,
        "dconst": 29,
        "dintel": null,
        "dwisdom": 15,
        "dluck": 27,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 8,
        "name": "Рейджер",
        "name_en": "Ranger",
        "parent": 0,
        "parent_name": null,
        "number": 1,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 9,
        "name": "Стрелок",
        "name_en": "Shooter",
        "parent": 8,
        "parent_name": "Ranger",
        "number": 1,
        "minstrength": 11,
        "mindexterity": 27,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": 22,
        "minlevel": 8,
        "dstrength": 4,
        "ddexterity": null,
        "dreaction": 2,
        "dconst": 4,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 10,
        "name": "Лучник",
        "name_en": "Archer",
        "parent": 8,
        "parent_name": "Ranger",
        "number": 2,
        "minstrength": 18,
        "mindexterity": 41,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": 32,
        "minlevel": 11,
        "dstrength": 9,
        "ddexterity": null,
        "dreaction": 4,
        "dconst": 6,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 3,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 11,
        "name": "Егерь",
        "name_en": "Huntsman",
        "parent": 8,
        "parent_name": "Ranger",
        "number": 3,
        "minstrength": 25,
        "mindexterity": 55,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": 45,
        "minlevel": 14,
        "dstrength": 20,
        "ddexterity": null,
        "dreaction": 9,
        "dconst": 14,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 8,
        "bodyarmor": 10,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 12,
        "name": "Снайпер",
        "name_en": "Sniper",
        "parent": 8,
        "parent_name": "Ranger",
        "number": 4,
        "minstrength": 39,
        "mindexterity": 69,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": 59,
        "minlevel": 17,
        "dstrength": 29,
        "ddexterity": null,
        "dreaction": 15,
        "dconst": 20,
        "dintel": null,
        "dwisdom": null,
        "dluck": 6,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 8,
        "bodyarmor": 10,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 13,
        "name": "Древний",
        "name_en": "Ancient",
        "parent": 8,
        "parent_name": "Ranger",
        "number": 5,
        "minstrength": 50,
        "mindexterity": 80,
        "minreaction": null,
        "minconst": 43,
        "minintel": null,
        "minwisdom": null,
        "minluck": 71,
        "minlevel": 20,
        "dstrength": 32,
        "ddexterity": null,
        "dreaction": 18,
        "dconst": 23,
        "dintel": null,
        "dwisdom": null,
        "dluck": 9,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 10,
        "bodyarmor": 10,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": 7
    },
    {
        "id": 14,
        "name": "Завоеватель",
        "name_en": "Conqueror",
        "parent": 8,
        "parent_name": "Ranger",
        "number": 6,
        "minstrength": 65,
        "mindexterity": 98,
        "minreaction": null,
        "minconst": 51,
        "minintel": null,
        "minwisdom": null,
        "minluck": 88,
        "minlevel": 23,
        "dstrength": 35,
        "ddexterity": null,
        "dreaction": 20,
        "dconst": 25,
        "dintel": null,
        "dwisdom": null,
        "dluck": 10,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 11,
        "bodyarmor": 11,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": 8
    },
    {
        "id": 15,
        "name": "Варвар",
        "name_en": "Barbarian",
        "parent": 0,
        "parent_name": null,
        "number": 2,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 16,
        "name": "Рубака",
        "name_en": "Cutter",
        "parent": 15,
        "parent_name": "Barbarian",
        "number": 1,
        "minstrength": 27,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 14,
        "minintel": null,
        "minwisdom": null,
        "minluck": 18,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": 4,
        "dreaction": null,
        "dconst": 4,
        "dintel": null,
        "dwisdom": null,
        "dluck": 2,
        "astralmagicprotection": null,
        "whitemagicprotection": 1,
        "blackmagicprotection": 1,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 17,
        "name": "Гладиатор",
        "name_en": "Gladiator",
        "parent": 15,
        "parent_name": "Barbarian",
        "number": 2,
        "minstrength": 41,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 22,
        "minintel": null,
        "minwisdom": null,
        "minluck": 30,
        "minlevel": 11,
        "dstrength": null,
        "ddexterity": 6,
        "dreaction": null,
        "dconst": 9,
        "dintel": null,
        "dwisdom": null,
        "dluck": 6,
        "astralmagicprotection": null,
        "whitemagicprotection": 2,
        "blackmagicprotection": 2,
        "headarmor": null,
        "bodyarmor": 3,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 18,
        "name": "Берсерк",
        "name_en": "Berserker",
        "parent": 15,
        "parent_name": "Barbarian",
        "number": 3,
        "minstrength": 55,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 36,
        "minintel": null,
        "minwisdom": null,
        "minluck": 45,
        "minlevel": 14,
        "dstrength": null,
        "ddexterity": 13,
        "dreaction": null,
        "dconst": 13,
        "dintel": null,
        "dwisdom": null,
        "dluck": 10,
        "astralmagicprotection": null,
        "whitemagicprotection": 6,
        "blackmagicprotection": 5,
        "headarmor": 5,
        "bodyarmor": 13,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 19,
        "name": "Вождь",
        "name_en": "Chieftain",
        "parent": 15,
        "parent_name": "Barbarian",
        "number": 4,
        "minstrength": 71,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 55,
        "minintel": null,
        "minwisdom": null,
        "minluck": 62,
        "minlevel": 17,
        "dstrength": null,
        "ddexterity": 21,
        "dreaction": null,
        "dconst": 21,
        "dintel": null,
        "dwisdom": null,
        "dluck": 16,
        "astralmagicprotection": null,
        "whitemagicprotection": 10,
        "blackmagicprotection": 9,
        "headarmor": 5,
        "bodyarmor": 13,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 20,
        "name": "Жнец",
        "name_en": "Reaper",
        "parent": 15,
        "parent_name": "Barbarian",
        "number": 5,
        "minstrength": 86,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 81,
        "minintel": null,
        "minwisdom": null,
        "minluck": 76,
        "minlevel": 20,
        "dstrength": null,
        "ddexterity": 25,
        "dreaction": null,
        "dconst": 25,
        "dintel": null,
        "dwisdom": null,
        "dluck": 20,
        "astralmagicprotection": null,
        "whitemagicprotection": 10,
        "blackmagicprotection": 10,
        "headarmor": 10,
        "bodyarmor": 15,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 21,
        "name": "Атаман",
        "name_en": "Ataman",
        "parent": 15,
        "parent_name": "Barbarian",
        "number": 6,
        "minstrength": 106,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 94,
        "minintel": null,
        "minwisdom": null,
        "minluck": 102,
        "minlevel": 23,
        "dstrength": null,
        "ddexterity": 27,
        "dreaction": null,
        "dconst": 27,
        "dintel": null,
        "dwisdom": null,
        "dluck": 22,
        "astralmagicprotection": null,
        "whitemagicprotection": 11,
        "blackmagicprotection": 11,
        "headarmor": 11,
        "bodyarmor": 16,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 22,
        "name": "Мастер щита",
        "name_en": "Shield master",
        "parent": 0,
        "parent_name": null,
        "number": 3,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 23,
        "name": "Щитоносец",
        "name_en": "Shieldbearer",
        "parent": 22,
        "parent_name": "Shield master",
        "number": 1,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": 22,
        "minconst": 27,
        "minintel": null,
        "minwisdom": null,
        "minluck": 12,
        "minlevel": 8,
        "dstrength": 5,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": 2,
        "dwisdom": null,
        "dluck": 3,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 24,
        "name": "Легионер",
        "name_en": "Legionary",
        "parent": 22,
        "parent_name": "Shield master",
        "number": 2,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": 32,
        "minconst": 41,
        "minintel": null,
        "minwisdom": null,
        "minluck": 24,
        "minlevel": 11,
        "dstrength": 11,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 2,
        "dintel": 4,
        "dwisdom": null,
        "dluck": 6,
        "astralmagicprotection": null,
        "whitemagicprotection": 2,
        "blackmagicprotection": 2,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 25,
        "name": "Центурион",
        "name_en": "Centurion",
        "parent": 22,
        "parent_name": "Shield master",
        "number": 3,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": 45,
        "minconst": 55,
        "minintel": null,
        "minwisdom": null,
        "minluck": 42,
        "minlevel": 14,
        "dstrength": 17,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 4,
        "dintel": 7,
        "dwisdom": null,
        "dluck": 11,
        "astralmagicprotection": null,
        "whitemagicprotection": 8,
        "blackmagicprotection": 8,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 26,
        "name": "Чемпион",
        "name_en": "Champion",
        "parent": 22,
        "parent_name": "Shield master",
        "number": 4,
        "minstrength": 20,
        "mindexterity": null,
        "minreaction": 53,
        "minconst": 61,
        "minintel": null,
        "minwisdom": null,
        "minluck": 51,
        "minlevel": 17,
        "dstrength": 23,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 16,
        "dintel": 11,
        "dwisdom": null,
        "dluck": 16,
        "astralmagicprotection": null,
        "whitemagicprotection": 8,
        "blackmagicprotection": 8,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 27,
        "name": "Монолит",
        "name_en": "Monolith",
        "parent": 22,
        "parent_name": "Shield master",
        "number": 5,
        "minstrength": 20,
        "mindexterity": null,
        "minreaction": 75,
        "minconst": 78,
        "minintel": null,
        "minwisdom": null,
        "minluck": 77,
        "minlevel": 20,
        "dstrength": 26,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 19,
        "dintel": 14,
        "dwisdom": null,
        "dluck": 19,
        "astralmagicprotection": null,
        "whitemagicprotection": 10,
        "blackmagicprotection": 10,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 28,
        "name": "Полководец",
        "name_en": "Commander",
        "parent": 22,
        "parent_name": "Shield master",
        "number": 6,
        "minstrength": 20,
        "mindexterity": null,
        "minreaction": 92,
        "minconst": 95,
        "minintel": null,
        "minwisdom": null,
        "minluck": 95,
        "minlevel": 23,
        "dstrength": 29,
        "ddexterity": null,
        "dreaction": null,
        "dconst": 21,
        "dintel": 15,
        "dwisdom": null,
        "dluck": 21,
        "astralmagicprotection": null,
        "whitemagicprotection": 11,
        "blackmagicprotection": 11,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 29,
        "name": "Жрец",
        "name_en": "Priest",
        "parent": 0,
        "parent_name": null,
        "number": 5,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": null,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 30,
        "name": "Священник",
        "name_en": "Priest",
        "parent": 29,
        "parent_name": "Priest",
        "number": 1,
        "minstrength": 21,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 17,
        "minintel": 22,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": 3,
        "dconst": null,
        "dintel": null,
        "dwisdom": 4,
        "dluck": 3,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 31,
        "name": "Клирик",
        "name_en": "Cleric",
        "parent": 29,
        "parent_name": "Priest",
        "number": 2,
        "minstrength": 31,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 30,
        "minintel": 35,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 11,
        "dstrength": null,
        "ddexterity": 1,
        "dreaction": 7,
        "dconst": null,
        "dintel": 2,
        "dwisdom": 8,
        "dluck": 7,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 32,
        "name": "Крестоносец",
        "name_en": "Crusader",
        "parent": 29,
        "parent_name": "Priest",
        "number": 3,
        "minstrength": 45,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 45,
        "minintel": 50,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 14,
        "dstrength": null,
        "ddexterity": 6,
        "dreaction": 13,
        "dconst": null,
        "dintel": 4,
        "dwisdom": 14,
        "dluck": 12,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 33,
        "name": "Паладин",
        "name_en": "Paladin",
        "parent": 29,
        "parent_name": "Priest",
        "number": 4,
        "minstrength": 54,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 55,
        "minintel": 56,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 17,
        "dstrength": null,
        "ddexterity": 12,
        "dreaction": 19,
        "dconst": null,
        "dintel": 6,
        "dwisdom": 21,
        "dluck": 18,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 34,
        "name": "Епископ",
        "name_en": "Bishop",
        "parent": 29,
        "parent_name": "Priest",
        "number": 5,
        "minstrength": 78,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 72,
        "minintel": 76,
        "minwisdom": 20,
        "minluck": null,
        "minlevel": 20,
        "dstrength": null,
        "ddexterity": 15,
        "dreaction": 22,
        "dconst": null,
        "dintel": 9,
        "dwisdom": 24,
        "dluck": 21,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 1,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 35,
        "name": "Кардинал",
        "name_en": "Cardinal",
        "parent": 29,
        "parent_name": "Priest",
        "number": 6,
        "minstrength": 97,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 91,
        "minintel": 94,
        "minwisdom": 20,
        "minluck": null,
        "minlevel": 23,
        "dstrength": null,
        "ddexterity": 16,
        "dreaction": 24,
        "dconst": null,
        "dintel": 10,
        "dwisdom": 26,
        "dluck": 23,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 1,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 36,
        "name": "Маг",
        "name_en": "Mage",
        "parent": 0,
        "parent_name": null,
        "number": 6,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": null,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": null,
        "dstrength": null,
        "ddexterity": null,
        "dreaction": null,
        "dconst": null,
        "dintel": null,
        "dwisdom": null,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 37,
        "name": "Посвящённый",
        "name_en": "Initiate",
        "parent": 36,
        "parent_name": "Mage",
        "number": 1,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 12,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 8,
        "dstrength": null,
        "ddexterity": 1,
        "dreaction": null,
        "dconst": 4,
        "dintel": null,
        "dwisdom": 5,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": null,
        "bodyarmor": null,
        "lefthandarmor": null,
        "righthandarmor": null,
        "lagsarmor": null
    },
    {
        "id": 38,
        "name": "Аколит",
        "name_en": "Acolyte",
        "parent": 36,
        "parent_name": "Mage",
        "number": 2,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 21,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 11,
        "dstrength": null,
        "ddexterity": 2,
        "dreaction": null,
        "dconst": 9,
        "dintel": 1,
        "dwisdom": 11,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 1,
        "bodyarmor": 1,
        "lefthandarmor": 1,
        "righthandarmor": 1,
        "lagsarmor": 1
    },
    {
        "id": 39,
        "name": "Адепт",
        "name_en": "Adept",
        "parent": 36,
        "parent_name": "Mage",
        "number": 3,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 25,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 14,
        "dstrength": null,
        "ddexterity": 4,
        "dreaction": null,
        "dconst": 15,
        "dintel": 2,
        "dwisdom": 19,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 5,
        "bodyarmor": 5,
        "lefthandarmor": 5,
        "righthandarmor": 5,
        "lagsarmor": 5
    },
    {
        "id": 40,
        "name": "Магистр",
        "name_en": "Magister",
        "parent": 36,
        "parent_name": "Mage",
        "number": 4,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 37,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 17,
        "dstrength": null,
        "ddexterity": 7,
        "dreaction": null,
        "dconst": 22,
        "dintel": 3,
        "dwisdom": 28,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 10,
        "bodyarmor": 10,
        "lefthandarmor": 10,
        "righthandarmor": 10,
        "lagsarmor": 10
    },
    {
        "id": 41,
        "name": "Патриарх",
        "name_en": "Patriarh",
        "parent": 36,
        "parent_name": "Mage",
        "number": 5,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 51,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 20,
        "dstrength": null,
        "ddexterity": 10,
        "dreaction": null,
        "dconst": 25,
        "dintel": 6,
        "dwisdom": 31,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 12,
        "bodyarmor": 12,
        "lefthandarmor": 12,
        "righthandarmor": 12,
        "lagsarmor": 12
    },
    {
        "id": 42,
        "name": "Властелин",
        "name_en": "Overlord",
        "parent": 36,
        "parent_name": "Mage",
        "number": 6,
        "minstrength": null,
        "mindexterity": null,
        "minreaction": null,
        "minconst": 71,
        "minintel": null,
        "minwisdom": null,
        "minluck": null,
        "minlevel": 23,
        "dstrength": null,
        "ddexterity": 11,
        "dreaction": null,
        "dconst": 27,
        "dintel": 7,
        "dwisdom": 34,
        "dluck": null,
        "astralmagicprotection": null,
        "whitemagicprotection": null,
        "blackmagicprotection": null,
        "headarmor": 13,
        "bodyarmor": 13,
        "lefthandarmor": 13,
        "righthandarmor": 13,
        "lagsarmor": 13
    }
]


export const fortressParam = [
{ name: 'Новичок', id: 'newbie'},
{ name: 'Продвинутий', id: 'promotions'},
{ name: 'Експерт', id: 'expert'},
{ name: 'Мастер', id: 'master'},
{ name: 'Грандмастер', id: 'grandmaster'},
]

export const raseParams = [
    { name: 'Человек', id: 'human'},
    { name: 'Гном', id: 'gnom'},
    { name: 'Эльф', id: 'elf'},
    { name: 'Вампир', id: 'vampire'},
    { name: 'Орк', id: 'ork'},
    { name: 'Троль', id: 'trol'},
    ]

      