
export const baseDummyParams = [
    { location: 'dummyPartLeft', name: 'helmet', link: 'src/assets/img/helmet.png' },
    { location: 'dummyPartLeft', name: 'armor', link: 'src/assets/img/armor.png' },
    { location: 'dummyPartLeft', name: 'belt', link: 'src/assets/img/belt.png' },
    { location: 'dummyPartLeft', name: 'boots', link: 'src/assets/img/boots.png' },
    { location: 'dummyPartLeft', name: 'earring', link: 'src/assets/img/earring.png' },
    { location: 'dummyPartLeft', name: 'ring1', link: 'src/assets/img/ring.png' },
    { location: 'dummyPartLeft', name: 'ring2', link: 'src/assets/img/ring.png' },
    { location: 'dummyPartRight', name: 'necklace', link: 'src/assets/img/necklace.png' },
    { location: 'dummyPartRight', name: 'bracers', link: 'src/assets/img/bracers.png' },
    { location: 'dummyPartRight', name: 'gloves', link: 'src/assets/img/gloves.png' },
    { location: 'dummyPartRight', name: 'leggings', link: 'src/assets/img/leggings.png' },
    { location: 'dummyPartRight', name: 'earring', link: 'src/assets/img/earring.png' },
    { location: 'dummyPartRight', name: 'ring3', link: 'src/assets/img/ring.png' },
    { location: 'dummyPartRight', name: 'ring4', link: 'src/assets/img/ring.png' },
    { location: 'dummyPartCenterTop', name: 'relic1', link: 'src/assets/img/relic.png' },
    { location: 'dummyPartCenterTop', name: 'relic2', link: 'src/assets/img/relic.png' },
    { location: 'dummyPartCenterTop', name: 'relic3', link: 'src/assets/img/relic.png' },
    { location: 'dummyPartCenterTop', name: 'relic4', link: 'src/assets/img/relic.png' },
    { location: 'dummyPartCenterBottom', name: 'weapons1', link: 'src/assets/img/weapons.png' },
    { location: 'dummyPartCenterBottom', name: 'weapons2', link: 'src/assets/img/weapons.png' },
  ]


export const baseParam = [
  { type: 'stat', key: 'strength_bonus', name: 'Сила', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/strength.svg' },
  { type: 'stat', key: 'dexterity_bonus', name: 'Ловкість', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/dexterity.svg' },
  { type: 'stat', key: 'intelligence_bonus', name: 'Інтелект', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/intelligence.svg' },
  { type: 'stat', key: 'luck_bonus', name: 'Удача', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/luck.svg' },
  { type: 'stat', key: 'reaction_bonus', name: 'Реакція', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/reaction.svg' },
  { type: 'stat', key: 'wisdom_bonus', name: 'Мудрість', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/wisdom.svg' },
  { type: 'stat', key: 'constitution_bonus', name: 'Статура', summStatBase: 3, summStatBaseOll: 3, link: 'src/assets/img/icon/svg/constitution.svg' },
  { type: 'protectionMagick', key: 'dawn_bonus', name: 'Світанок', summStatBaseOll: 6, link: 'src/assets/img/icon/svg/dawn.svg' },
  { type: 'protectionMagick', key: 'fullMoon_bonus', name: 'Полнолуння', summStatBaseOll: 6, link: 'src/assets/img/icon/svg/full-Moon.svg' },
  { type: 'protectionMagick', key: 'astral_bonus', name: 'Астрал', summStatBaseOll: 4, link: 'src/assets/img/icon/svg/astral.svg' },
  { type: 'armor', key: 'headArmor_bonus', name: 'Голова', summStatBaseOll: 0, link: 'src/assets/img/icon/svg/armor_head.svg' },
  { type: 'armor', key: 'bodyArmor_bonus', name: 'Тулуб', summStatBaseOll: 0, link: 'src/assets/img/icon/svg/armor.svg' },
  { type: 'armor', key: 'leftHand_bonus', name: 'Ліва рука', summStatBaseOll: 0, link: 'src/assets/img/icon/svg/leftHend.svg' },
  { type: 'armor', key: 'rightHand_bonus', name: 'Права рука', summStatBaseOll: 0, link: 'src/assets/img/icon/svg/rightHend.svg' },
  { type: 'armor', key: 'legsArmor_bonus', name: 'Ноги', summStatBaseOll: 0, link: 'src/assets/img/icon/svg/leg-armor.svg' },
]

export const basickParamsRase = [
  {
    rase: 'human', date: [
      {key: 'strength_bonus', count: 3 },
      {key: 'dexterity_bonus', count: 3 },
      {key: 'intelligence_bonus', count: 3 },
      {key: 'luck_bonus', count: 3 },
      {key: 'reaction_bonus', count: 3 },
      {key: 'wisdom_bonus', count: 3 },
      {key: 'constitution_bonus', count: 3 },
      {key: 'dawn_bonus', count: 6 },
      {key: 'fullMoon_bonus', count: 6 },
      {key: 'astral_bonus', count: 4 },
    ]
  },
  {
    rase: 'gnom', date: [
      {key: 'strength_bonus', count: 4 },
      {key: 'dexterity_bonus', count: 2 },
      {key: 'intelligence_bonus', count: 2 },
      {key: 'luck_bonus', count: 3 },
      {key: 'reaction_bonus', count: 2 },
      {key: 'wisdom_bonus', count: 4 },
      {key: 'constitution_bonus', count: 4 },
      {key: 'dawn_bonus', count: 4 },
      {key: 'fullMoon_bonus', count: 8 },
      {key: 'astral_bonus', count: 4 },
    ]
  },
  {
    rase: 'elf', date: [
      {key: 'strength_bonus', count: 3 },
      {key: 'dexterity_bonus', count: 5 },
      {key: 'intelligence_bonus', count: 3 },
      {key: 'luck_bonus', count: 2 },
      {key: 'reaction_bonus', count: 2 },
      {key: 'wisdom_bonus', count: 3 },
      {key: 'constitution_bonus', count: 3 },
      {key: 'dawn_bonus', count: 8 },
      {key: 'fullMoon_bonus', count: 4 },
      {key: 'astral_bonus', count: 4 },
    ]
  },
  {
    rase: 'vampire', date: [
      {key: 'strength_bonus', count: 3 },
      {key: 'dexterity_bonus', count: 3 },
      {key: 'intelligence_bonus', count: 3 },
      {key: 'luck_bonus', count: 4 },
      {key: 'reaction_bonus', count: 2 },
      {key: 'wisdom_bonus', count: 3 },
      {key: 'constitution_bonus', count: 3 },
      {key: 'dawn_bonus', count: 6 },
      {key: 'fullMoon_bonus', count: 6 },
      {key: 'astral_bonus', count: 4 },
    ]
  },
  {
    rase: 'ork', date: [
      {key: 'strength_bonus', count: 4 },
      {key: 'dexterity_bonus', count: 3 },
      {key: 'intelligence_bonus', count: 2 },
      {key: 'luck_bonus', count: 4 },
      {key: 'reaction_bonus', count: 3 },
      {key: 'wisdom_bonus', count: 1 },
      {key: 'constitution_bonus', count: 4 },
      {key: 'dawn_bonus', count: 9 },
      {key: 'fullMoon_bonus', count: 9 },
      {key: 'astral_bonus', count: 0 },
    ]
  },
  {
    rase: 'trol', date: [
      {key: 'strength_bonus', count: 5 },
      {key: 'dexterity_bonus', count: 2 },
      {key: 'intelligence_bonus', count: 1 },
      {key: 'luck_bonus', count: 3 },
      {key: 'reaction_bonus', count: 3 },
      {key: 'wisdom_bonus', count: 2 },
      {key: 'constitution_bonus', count: 5 },
      {key: 'dawn_bonus', count: 7 },
      {key: 'fullMoon_bonus', count: 5 },
      {key: 'astral_bonus', count: 4 },
      {key: 'fortress', count: 1 },
    ]
  },
]

// массив для работы пока создается
export const baseStatClasses = [
  {
      "id": "1",
      "name": "Джаггернаут",
      "name_en": "Juggernaut",
      "parent": "0",
      "parent_name": null,
      "number": "4",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "2",
      "name": "Защитник",
      "name_en": "Defender",
      "parent": "1",
      "parent_name": "Juggernaut",
      "number": "1",
      "strength_req": "16",
      "dexterity_req": null,
      "reaction_req": "12",
      "constitution_req": "29",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "4",
      "intelligence_bonus": null,
      "wisdom_bonus": "2",
      "luck_bonus": "4",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "3",
      "name": "Гвардеец",
      "name_en": "Guardsman",
      "parent": "1",
      "parent_name": "Juggernaut",
      "number": "2",
      "strength_req": "27",
      "dexterity_req": null,
      "reaction_req": "18",
      "constitution_req": "44",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "11",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "9",
      "intelligence_bonus": null,
      "wisdom_bonus": "4",
      "luck_bonus": "8",
      "astral_bonus": "2",
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "4",
      "name": "Рыцарь",
      "name_en": "Knight",
      "parent": "1",
      "parent_name": "Juggernaut",
      "number": "3",
      "strength_req": "39",
      "dexterity_req": null,
      "reaction_req": "28",
      "constitution_req": "62",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "14",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "16",
      "intelligence_bonus": null,
      "wisdom_bonus": "7",
      "luck_bonus": "15",
      "astral_bonus": "7",
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "5",
      "name": "Кавалер",
      "name_en": "Cavalier",
      "parent": "1",
      "parent_name": "Juggernaut",
      "number": "4",
      "strength_req": "51",
      "dexterity_req": null,
      "reaction_req": "35",
      "constitution_req": "86",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "20",
      "lvl_req": "17",
      "strength_bonus": null,
      "dexterity_bonus": "7",
      "reaction_bonus": null,
      "constitution_bonus": "23",
      "intelligence_bonus": null,
      "wisdom_bonus": "11",
      "luck_bonus": "22",
      "astral_bonus": "7",
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "6",
      "name": "Титан",
      "name_en": "Titan",
      "parent": "1",
      "parent_name": "Juggernaut",
      "number": "5",
      "strength_req": "60",
      "dexterity_req": null,
      "reaction_req": "43",
      "constitution_req": "100",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "42",
      "lvl_req": "20",
      "strength_bonus": null,
      "dexterity_bonus": "10",
      "reaction_bonus": null,
      "constitution_bonus": "26",
      "intelligence_bonus": null,
      "wisdom_bonus": "14",
      "luck_bonus": "25",
      "astral_bonus": "8",
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "7",
      "name": "Исполин",
      "name_en": "Nephilim",
      "parent": "1",
      "parent_name": "Juggernaut",
      "number": "6",
      "strength_req": "75",
      "dexterity_req": null,
      "reaction_req": "58",
      "constitution_req": "115",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "57",
      "lvl_req": "23",
      "strength_bonus": null,
      "dexterity_bonus": "11",
      "reaction_bonus": null,
      "constitution_bonus": "29",
      "intelligence_bonus": null,
      "wisdom_bonus": "15",
      "luck_bonus": "27",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "8",
      "name": "Рейджер",
      "name_en": "Ranger",
      "parent": "0",
      "parent_name": null,
      "number": "1",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "9",
      "name": "Стрелок",
      "name_en": "Shooter",
      "parent": "8",
      "parent_name": "Ranger",
      "number": "1",
      "strength_req": "11",
      "dexterity_req": "27",
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "22",
      "lvl_req": "8",
      "strength_bonus": "4",
      "dexterity_bonus": null,
      "reaction_bonus": "2",
      "constitution_bonus": "4",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "10",
      "name": "Лучник",
      "name_en": "Archer",
      "parent": "8",
      "parent_name": "Ranger",
      "number": "2",
      "strength_req": "18",
      "dexterity_req": "41",
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "32",
      "lvl_req": "11",
      "strength_bonus": "9",
      "dexterity_bonus": null,
      "reaction_bonus": "4",
      "constitution_bonus": "6",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "3",
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "11",
      "name": "Егерь",
      "name_en": "Huntsman",
      "parent": "8",
      "parent_name": "Ranger",
      "number": "3",
      "strength_req": "25",
      "dexterity_req": "55",
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "45",
      "lvl_req": "14",
      "strength_bonus": "20",
      "dexterity_bonus": null,
      "reaction_bonus": "9",
      "constitution_bonus": "14",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "8",
      "bodyArmor_bonus": "10",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "12",
      "name": "Снайпер",
      "name_en": "Sniper",
      "parent": "8",
      "parent_name": "Ranger",
      "number": "4",
      "strength_req": "39",
      "dexterity_req": "69",
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "59",
      "lvl_req": "17",
      "strength_bonus": "29",
      "dexterity_bonus": null,
      "reaction_bonus": "15",
      "constitution_bonus": "20",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "6",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "8",
      "bodyArmor_bonus": "10",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "13",
      "name": "Древний",
      "name_en": "Ancient",
      "parent": "8",
      "parent_name": "Ranger",
      "number": "5",
      "strength_req": "50",
      "dexterity_req": "80",
      "reaction_req": null,
      "constitution_req": "43",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "71",
      "lvl_req": "20",
      "strength_bonus": "32",
      "dexterity_bonus": null,
      "reaction_bonus": "18",
      "constitution_bonus": "23",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "9",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "10",
      "bodyArmor_bonus": "10",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": "7"
  },
  {
      "id": "14",
      "name": "Завоеватель",
      "name_en": "Conqueror",
      "parent": "8",
      "parent_name": "Ranger",
      "number": "6",
      "strength_req": "65",
      "dexterity_req": "98",
      "reaction_req": null,
      "constitution_req": "51",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "88",
      "lvl_req": "23",
      "strength_bonus": "35",
      "dexterity_bonus": null,
      "reaction_bonus": "20",
      "constitution_bonus": "25",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "10",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "11",
      "bodyArmor_bonus": "11",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": "8"
  },
  {
      "id": "15",
      "name": "Варвар",
      "name_en": "Barbarian",
      "parent": "0",
      "parent_name": null,
      "number": "2",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "16",
      "name": "Рубака",
      "name_en": "Cutter",
      "parent": "15",
      "parent_name": "Barbarian",
      "number": "1",
      "strength_req": "27",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "14",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "18",
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": "4",
      "reaction_bonus": null,
      "constitution_bonus": "4",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "2",
      "astral_bonus": null,
      "dawn_bonus": "1",
      "fullMoon_bonus": "1",
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "17",
      "name": "Гладиатор",
      "name_en": "Gladiator",
      "parent": "15",
      "parent_name": "Barbarian",
      "number": "2",
      "strength_req": "41",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "22",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "30",
      "lvl_req": "11",
      "strength_bonus": null,
      "dexterity_bonus": "6",
      "reaction_bonus": null,
      "constitution_bonus": "9",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "6",
      "astral_bonus": null,
      "dawn_bonus": "2",
      "fullMoon_bonus": "2",
      "headArmor_bonus": null,
      "bodyArmor_bonus": "3",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "18",
      "name": "Берсерк",
      "name_en": "Berserker",
      "parent": "15",
      "parent_name": "Barbarian",
      "number": "3",
      "strength_req": "55",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "36",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "45",
      "lvl_req": "14",
      "strength_bonus": null,
      "dexterity_bonus": "13",
      "reaction_bonus": null,
      "constitution_bonus": "13",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "10",
      "astral_bonus": null,
      "dawn_bonus": "6",
      "fullMoon_bonus": "5",
      "headArmor_bonus": "5",
      "bodyArmor_bonus": "13",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "19",
      "name": "Вождь",
      "name_en": "Chieftain",
      "parent": "15",
      "parent_name": "Barbarian",
      "number": "4",
      "strength_req": "71",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "55",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "62",
      "lvl_req": "17",
      "strength_bonus": null,
      "dexterity_bonus": "21",
      "reaction_bonus": null,
      "constitution_bonus": "21",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "16",
      "astral_bonus": null,
      "dawn_bonus": "10",
      "fullMoon_bonus": "9",
      "headArmor_bonus": "5",
      "bodyArmor_bonus": "13",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "20",
      "name": "Жнец",
      "name_en": "Reaper",
      "parent": "15",
      "parent_name": "Barbarian",
      "number": "5",
      "strength_req": "86",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "81",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "76",
      "lvl_req": "20",
      "strength_bonus": null,
      "dexterity_bonus": "25",
      "reaction_bonus": null,
      "constitution_bonus": "25",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "20",
      "astral_bonus": null,
      "dawn_bonus": "10",
      "fullMoon_bonus": "10",
      "headArmor_bonus": "10",
      "bodyArmor_bonus": "15",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "21",
      "name": "Атаман",
      "name_en": "Ataman",
      "parent": "15",
      "parent_name": "Barbarian",
      "number": "6",
      "strength_req": "106",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "94",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "102",
      "lvl_req": "23",
      "strength_bonus": null,
      "dexterity_bonus": "27",
      "reaction_bonus": null,
      "constitution_bonus": "27",
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": "22",
      "astral_bonus": null,
      "dawn_bonus": "11",
      "fullMoon_bonus": "11",
      "headArmor_bonus": "11",
      "bodyArmor_bonus": "16",
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "22",
      "name": "Мастер щита",
      "name_en": "Shield master",
      "parent": "0",
      "parent_name": null,
      "number": "3",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "23",
      "name": "Щитоносец",
      "name_en": "Shieldbearer",
      "parent": "22",
      "parent_name": "Shield master",
      "number": "1",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": "22",
      "constitution_req": "27",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "12",
      "lvl_req": "8",
      "strength_bonus": "5",
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": "2",
      "wisdom_bonus": null,
      "luck_bonus": "3",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "24",
      "name": "Легионер",
      "name_en": "Legionary",
      "parent": "22",
      "parent_name": "Shield master",
      "number": "2",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": "32",
      "constitution_req": "41",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "24",
      "lvl_req": "11",
      "strength_bonus": "11",
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "2",
      "intelligence_bonus": "4",
      "wisdom_bonus": null,
      "luck_bonus": "6",
      "astral_bonus": null,
      "dawn_bonus": "2",
      "fullMoon_bonus": "2",
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "25",
      "name": "Центурион",
      "name_en": "Centurion",
      "parent": "22",
      "parent_name": "Shield master",
      "number": "3",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": "45",
      "constitution_req": "55",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "42",
      "lvl_req": "14",
      "strength_bonus": "17",
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "4",
      "intelligence_bonus": "7",
      "wisdom_bonus": null,
      "luck_bonus": "11",
      "astral_bonus": null,
      "dawn_bonus": "8",
      "fullMoon_bonus": "8",
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "26",
      "name": "Чемпион",
      "name_en": "Champion",
      "parent": "22",
      "parent_name": "Shield master",
      "number": "4",
      "strength_req": "20",
      "dexterity_req": null,
      "reaction_req": "53",
      "constitution_req": "61",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "51",
      "lvl_req": "17",
      "strength_bonus": "23",
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "16",
      "intelligence_bonus": "11",
      "wisdom_bonus": null,
      "luck_bonus": "16",
      "astral_bonus": null,
      "dawn_bonus": "8",
      "fullMoon_bonus": "8",
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "27",
      "name": "Монолит",
      "name_en": "Monolith",
      "parent": "22",
      "parent_name": "Shield master",
      "number": "5",
      "strength_req": "20",
      "dexterity_req": null,
      "reaction_req": "75",
      "constitution_req": "78",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "77",
      "lvl_req": "20",
      "strength_bonus": "26",
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "19",
      "intelligence_bonus": "14",
      "wisdom_bonus": null,
      "luck_bonus": "19",
      "astral_bonus": null,
      "dawn_bonus": "10",
      "fullMoon_bonus": "10",
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "28",
      "name": "Полководец",
      "name_en": "Commander",
      "parent": "22",
      "parent_name": "Shield master",
      "number": "6",
      "strength_req": "20",
      "dexterity_req": null,
      "reaction_req": "92",
      "constitution_req": "95",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": "95",
      "lvl_req": "23",
      "strength_bonus": "29",
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": "21",
      "intelligence_bonus": "15",
      "wisdom_bonus": null,
      "luck_bonus": "21",
      "astral_bonus": null,
      "dawn_bonus": "11",
      "fullMoon_bonus": "11",
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "29",
      "name": "Жрец",
      "name_en": "Priest",
      "parent": "0",
      "parent_name": null,
      "number": "5",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": null,
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "30",
      "name": "Священник",
      "name_en": "Priest",
      "parent": "29",
      "parent_name": "Priest",
      "number": "1",
      "strength_req": "21",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "17",
      "intelligence_req": "22",
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": "3",
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": "4",
      "luck_bonus": "3",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "31",
      "name": "Клирик",
      "name_en": "Cleric",
      "parent": "29",
      "parent_name": "Priest",
      "number": "2",
      "strength_req": "31",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "30",
      "intelligence_req": "35",
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "11",
      "strength_bonus": null,
      "dexterity_bonus": "1",
      "reaction_bonus": "7",
      "constitution_bonus": null,
      "intelligence_bonus": "2",
      "wisdom_bonus": "8",
      "luck_bonus": "7",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "32",
      "name": "Крестоносец",
      "name_en": "Crusader",
      "parent": "29",
      "parent_name": "Priest",
      "number": "3",
      "strength_req": "45",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "45",
      "intelligence_req": "50",
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "14",
      "strength_bonus": null,
      "dexterity_bonus": "6",
      "reaction_bonus": "13",
      "constitution_bonus": null,
      "intelligence_bonus": "4",
      "wisdom_bonus": "14",
      "luck_bonus": "12",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "33",
      "name": "Паладин",
      "name_en": "Paladin",
      "parent": "29",
      "parent_name": "Priest",
      "number": "4",
      "strength_req": "54",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "55",
      "intelligence_req": "56",
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "17",
      "strength_bonus": null,
      "dexterity_bonus": "12",
      "reaction_bonus": "19",
      "constitution_bonus": null,
      "intelligence_bonus": "6",
      "wisdom_bonus": "21",
      "luck_bonus": "18",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "34",
      "name": "Епископ",
      "name_en": "Bishop",
      "parent": "29",
      "parent_name": "Priest",
      "number": "5",
      "strength_req": "78",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "72",
      "intelligence_req": "76",
      "wisdom_req": "20",
      "luck_req": null,
      "lvl_req": "20",
      "strength_bonus": null,
      "dexterity_bonus": "15",
      "reaction_bonus": "22",
      "constitution_bonus": null,
      "intelligence_bonus": "9",
      "wisdom_bonus": "24",
      "luck_bonus": "21",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "1",
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "35",
      "name": "Кардинал",
      "name_en": "Cardinal",
      "parent": "29",
      "parent_name": "Priest",
      "number": "6",
      "strength_req": "97",
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "91",
      "intelligence_req": "94",
      "wisdom_req": "20",
      "luck_req": null,
      "lvl_req": "23",
      "strength_bonus": null,
      "dexterity_bonus": "16",
      "reaction_bonus": "24",
      "constitution_bonus": null,
      "intelligence_bonus": "10",
      "wisdom_bonus": "26",
      "luck_bonus": "23",
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "1",
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "36",
      "name": "Маг",
      "name_en": "Mage",
      "parent": "0",
      "parent_name": null,
      "number": "6",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": null,
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": null,
      "strength_bonus": null,
      "dexterity_bonus": null,
      "reaction_bonus": null,
      "constitution_bonus": null,
      "intelligence_bonus": null,
      "wisdom_bonus": null,
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "37",
      "name": "Посвящённый",
      "name_en": "Initiate",
      "parent": "36",
      "parent_name": "Mage",
      "number": "1",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "12",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "8",
      "strength_bonus": null,
      "dexterity_bonus": "1",
      "reaction_bonus": null,
      "constitution_bonus": "4",
      "intelligence_bonus": null,
      "wisdom_bonus": "5",
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": null,
      "bodyArmor_bonus": null,
      "leftHand_bonus": null,
      "rightHand_bonus": null,
      "legsArmor_bonus": null
  },
  {
      "id": "38",
      "name": "Аколит",
      "name_en": "Acolyte",
      "parent": "36",
      "parent_name": "Mage",
      "number": "2",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "21",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "11",
      "strength_bonus": null,
      "dexterity_bonus": "2",
      "reaction_bonus": null,
      "constitution_bonus": "9",
      "intelligence_bonus": "1",
      "wisdom_bonus": "11",
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "1",
      "bodyArmor_bonus": "1",
      "leftHand_bonus": "1",
      "rightHand_bonus": "1",
      "legsArmor_bonus": "1"
  },
  {
      "id": "39",
      "name": "Адепт",
      "name_en": "Adept",
      "parent": "36",
      "parent_name": "Mage",
      "number": "3",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "25",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "14",
      "strength_bonus": null,
      "dexterity_bonus": "4",
      "reaction_bonus": null,
      "constitution_bonus": "15",
      "intelligence_bonus": "2",
      "wisdom_bonus": "19",
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "5",
      "bodyArmor_bonus": "5",
      "leftHand_bonus": "5",
      "rightHand_bonus": "5",
      "legsArmor_bonus": "5"
  },
  {
      "id": "40",
      "name": "Магистр",
      "name_en": "Magister",
      "parent": "36",
      "parent_name": "Mage",
      "number": "4",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "37",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "17",
      "strength_bonus": null,
      "dexterity_bonus": "7",
      "reaction_bonus": null,
      "constitution_bonus": "22",
      "intelligence_bonus": "3",
      "wisdom_bonus": "28",
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "10",
      "bodyArmor_bonus": "10",
      "leftHand_bonus": "10",
      "rightHand_bonus": "10",
      "legsArmor_bonus": "10"
  },
  {
      "id": "41",
      "name": "Патриарх",
      "name_en": "Patriarh",
      "parent": "36",
      "parent_name": "Mage",
      "number": "5",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "51",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "20",
      "strength_bonus": null,
      "dexterity_bonus": "10",
      "reaction_bonus": null,
      "constitution_bonus": "25",
      "intelligence_bonus": "6",
      "wisdom_bonus": "31",
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "12",
      "bodyArmor_bonus": "12",
      "leftHand_bonus": "12",
      "rightHand_bonus": "12",
      "legsArmor_bonus": "12"
  },
  {
      "id": "42",
      "name": "Властелин",
      "name_en": "Overlord",
      "parent": "36",
      "parent_name": "Mage",
      "number": "6",
      "strength_req": null,
      "dexterity_req": null,
      "reaction_req": null,
      "constitution_req": "71",
      "intelligence_req": null,
      "wisdom_req": null,
      "luck_req": null,
      "lvl_req": "23",
      "strength_bonus": null,
      "dexterity_bonus": "11",
      "reaction_bonus": null,
      "constitution_bonus": "27",
      "intelligence_bonus": "7",
      "wisdom_bonus": "34",
      "luck_bonus": null,
      "astral_bonus": null,
      "dawn_bonus": null,
      "fullMoon_bonus": null,
      "headArmor_bonus": "13",
      "bodyArmor_bonus": "13",
      "leftHand_bonus": "13",
      "rightHand_bonus": "13",
      "legsArmor_bonus": "13"
  }
]