export const helm_10Lvl = [
    {
        "id": 39,
        "iddn": 10173,
        "price": "288",
        "goldprice": "3.2",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_helm75",
        "description": "Эти шлемы – еще одно доказательство того, что великими воинами не рождаются – ими становятся в ходе бесконечных тренировок. Когда джаггернаут уже вполне уверенно держит меч, его признают достойным носить такой шлем.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "21",
        "mindexterity": "0",
        "minconst": "39",
        "minintel": "0",
        "minwisdom": "0",
        "minluck": "0",
        "minreaction": "16",
        "durability": "490",
        "dstrength": "4",
        "ddexterity": "3",
        "dintel": "0",
        "dwisdom": "2",
        "dluck": "2",
        "dreaction": "3",
        "dconst": "5",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "37",
        "whitemagicprotection": "4",
        "blackmagicprotection": "4",
        "astralmagicprotection": "6",
        "rarity": "3",
        "dstamina": "0",
        "name": "Шлем воителя",
        "name_en": "Fighter's Helm"
    },
    {
        "id": 111,
        "iddn": 60,
        "price": "288",
        "goldprice": "0",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_helm21",
        "description": "Лицевая пластина шлема надежно защищает лицо от травм, а кольчужные кольца, которыми обрамлен шлем, дают свободу движений.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "15",
        "mindexterity": "34",
        "minconst": "0",
        "minintel": "0",
        "minwisdom": "0",
        "minluck": "28",
        "minreaction": "0",
        "durability": "255",
        "dstrength": "5",
        "ddexterity": "4",
        "dintel": "0",
        "dwisdom": "0",
        "dluck": "3",
        "dreaction": "0",
        "dconst": "3",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "20",
        "whitemagicprotection": "6",
        "blackmagicprotection": "6",
        "astralmagicprotection": "2",
        "rarity": "1",
        "dstamina": "0",
        "name": "Закрытый кольчужный шлем",
        "name_en": "Closed Mail Helmet"
    },
    {
        "id": 118,
        "iddn": 10164,
        "price": "288",
        "goldprice": "3.2",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_helm74",
        "description": "Капелланы – это служители Храма, которые путешествуют по Аквиллиону и уничтожают порождения скверны и ереси при первом их появлении. Шлемы их были сконструированы таким образом, чтобы ум жреца всегда был защищен от призывов Тьмы.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "26",
        "mindexterity": "0",
        "minconst": "25",
        "minintel": "29",
        "minwisdom": "0",
        "minluck": "0",
        "minreaction": "0",
        "durability": "260",
        "dstrength": "3",
        "ddexterity": "1",
        "dintel": "5",
        "dwisdom": "6",
        "dluck": "0",
        "dreaction": "0",
        "dconst": "4",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "22",
        "whitemagicprotection": "7",
        "blackmagicprotection": "7",
        "astralmagicprotection": "7",
        "rarity": "3",
        "dstamina": "0",
        "name": "Шлем капеллана",
        "name_en": "Chaplain's Helmet"
    },
    {
        "id": 144,
        "iddn": 61,
        "price": "288",
        "goldprice": "0",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_helm19",
        "description": "Стандартный шлем Имперских легионов, которые носили все без исключения легионеры. Изготовлен из высокопрочной стали, украшен стальным гребнем который в некоторых ситуациях мог служить и оружием в схватке.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "0",
        "mindexterity": "0",
        "minconst": "36",
        "minintel": "0",
        "minwisdom": "0",
        "minluck": "20",
        "minreaction": "28",
        "durability": "400",
        "dstrength": "1",
        "ddexterity": "0",
        "dintel": "0",
        "dwisdom": "0",
        "dluck": "5",
        "dreaction": "6",
        "dconst": "3",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "27",
        "whitemagicprotection": "5",
        "blackmagicprotection": "5",
        "astralmagicprotection": "1",
        "rarity": "1",
        "dstamina": "0",
        "name": "Имперский шлем",
        "name_en": "Imperial Helmet"
    },
    {
        "id": 2206,
        "iddn": 11919,
        "price": "288",
        "goldprice": "0",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_hlm10djag",
        "description": "Более легкий по сравнению с гвардейским, этот шлем обеспечивает куда лучший обзор поля боя. Стоит заметить что от такого решения несколько пострадала защищенность, но это не отпугивает потенциальных покупателей.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "21",
        "mindexterity": "0",
        "minconst": "39",
        "minintel": "0",
        "minwisdom": "0",
        "minluck": "0",
        "minreaction": "16",
        "durability": "405",
        "dstrength": "4",
        "ddexterity": "2",
        "dintel": "0",
        "dwisdom": "0",
        "dluck": "0",
        "dreaction": "4",
        "dconst": "5",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "27",
        "whitemagicprotection": "5",
        "blackmagicprotection": "5",
        "astralmagicprotection": "1",
        "rarity": "1",
        "dstamina": "0",
        "name": "Шлем телохранителя",
        "name_en": "Bodyguard's Helmet"
    },
    {
        "id": 2681,
        "iddn": 13264,
        "price": "288",
        "goldprice": "0",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_helm8",
        "description": "Пускай блестки осыпались, звездочка с навершия утеряна, а знаменитую надпись &quot;вАлшебник&quot; уже невозможно различить, эта шляпа еще славно послужит своему владельцу.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "0",
        "mindexterity": "0",
        "minconst": "17",
        "minintel": "30",
        "minwisdom": "36",
        "minluck": "0",
        "minreaction": "0",
        "durability": "180",
        "dstrength": "0",
        "ddexterity": "0",
        "dintel": "5",
        "dwisdom": "6",
        "dluck": "0",
        "dreaction": "0",
        "dconst": "4",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "10",
        "whitemagicprotection": "7",
        "blackmagicprotection": "7",
        "astralmagicprotection": "4",
        "rarity": "1",
        "dstamina": "0",
        "name": "Колдовская шляпа",
        "name_en": "Spellful Hat"
    },
    {
        "id": 2679,
        "iddn": 13260,
        "price": "288",
        "goldprice": "0",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_hlm10_jrec",
        "description": "Церковь крайне заботливо снабжает своих служителей всем необходимым., этот великолепный шлем не только придаст божественной силы и защитит монашескую тонзуру в пылу битвы, но и послужит в качестве удобного кубка или котелка.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "26",
        "mindexterity": "0",
        "minconst": "25",
        "minintel": "29",
        "minwisdom": "0",
        "minluck": "0",
        "minreaction": "0",
        "durability": "215",
        "dstrength": "3",
        "ddexterity": "0",
        "dintel": "5",
        "dwisdom": "4",
        "dluck": "0",
        "dreaction": "0",
        "dconst": "3",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "27",
        "whitemagicprotection": "5",
        "blackmagicprotection": "5",
        "astralmagicprotection": "1",
        "rarity": "1",
        "dstamina": "0",
        "name": "Позолоченный шлем священника",
        "name_en": "Gilded Helmet of the Clergyman"
    },
    {
        "id": 73,
        "iddn": 10985,
        "price": "288",
        "goldprice": "0",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_hlm10_var",
        "description": "Гномовержцы - тайный орден варваров, поставивший себе за цель истребление низкорослых жителей Аквиллиона. Ведомые слепой яростью и ненавистью, такие воины - опасные противники, и не только для гномов.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "24",
        "mindexterity": "0",
        "minconst": "0",
        "minintel": "0",
        "minwisdom": "0",
        "minluck": "18",
        "minreaction": "0",
        "durability": "280",
        "dstrength": "4",
        "ddexterity": "2",
        "dintel": "0",
        "dwisdom": "0",
        "dluck": "4",
        "dreaction": "1",
        "dconst": "4",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "25",
        "whitemagicprotection": "6",
        "blackmagicprotection": "5",
        "astralmagicprotection": "1",
        "rarity": "1",
        "dstamina": "0",
        "name": "Шлем гномовержца",
        "name_en": "Helm of the Dwarfplunger"
    },
    {
        "id": 36,
        "iddn": 10148,
        "price": "288",
        "goldprice": "3.2",
        "obmenprice": "0",
        "reliktprice": "0",
        "ratnikprice": "0",
        "artcrystalsprice": "0",
        "image": "image_helm71",
        "description": "Иллюзия рождается в голове человека, иллюзионист лишь поддерживает ее. Когда магу достаёт сил на контроль сознания живого существа – он становится Иллюзионистом и награждается такой повязкой.",
        "description_en": "",
        "minlevel": "10",
        "minstrength": "0",
        "mindexterity": "0",
        "minconst": "17",
        "minintel": "30",
        "minwisdom": "36",
        "minluck": "0",
        "minreaction": "0",
        "durability": "215",
        "dstrength": "0",
        "ddexterity": "0",
        "dintel": "8",
        "dwisdom": "7",
        "dluck": "0",
        "dreaction": "0",
        "dconst": "4",
        "handtype": "0",
        "range": "0",
        "mindamage": "0",
        "maxdamage": "0",
        "typeid": 1,
        "lagsarmor": "0",
        "bodyarmor": "0",
        "righthandarmor": "0",
        "lefthandarmor": "0",
        "headarmor": "20",
        "whitemagicprotection": "6",
        "blackmagicprotection": "6",
        "astralmagicprotection": "9",
        "rarity": "3",
        "dstamina": "0",
        "name": "Повязка иллюзиониста",
        "name_en": "Bandana of the Illusionist"
    }
]